In [2]:
import psycopg2
import pandas as pd

conn = psycopg2.connect(
    host="localhost",
    port=5432,
    database="trucking_ops",
    user="postgres",
    password="yournewpassword"
)

# List all tables
pd.read_sql_query("""
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = 'public'
    ORDER BY table_name;
""", conn)

C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\3187308237.py:13: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("""

                   table_name
0                   customers
1             delivery_events
2      driver_monthly_metrics
3                     drivers
4                  facilities
5              fuel_purchases
6                       loads
7         maintenance_records
8                      routes
9            safety_incidents
10                   trailers
11                      trips
12  truck_utilization_metrics
13                     trucks

In [3]:
tables = pd.read_sql_query("""
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = 'public'
    ORDER BY table_name;
""", conn)

C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\106597400.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  tables = pd.read_sql_query("""

In [4]:
for table in tables['table_name']:
    print(f"\n--- {table} ---")
    df = pd.read_sql_query(f"SELECT * FROM {table} LIMIT 3;", conn)
    display(df)

--- customers ---

C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\2727433777.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(f"SELECT * FROM {table} LIMIT 3;", conn)

,customer_id,customer_name,customer_type,credit_terms_days,primary_freight_type,account_status,contract_start_date,annual_revenue_potential
0,CUST00001,Metro Wholesale,Dedicated,60,General,Inactive,2020-02-20,985117.0
1,CUST00002,National Retail,Contract,30,Retail,Active,2021-06-02,4936566.0
2,CUST00003,XYZ Industries,Contract,30,Consumer Goods,Active,2020-09-04,3102814.0

--- delivery_events ---

C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\2727433777.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(f"SELECT * FROM {table} LIMIT 3;", conn)

,event_id,load_id,trip_id,event_type,facility_id,scheduled_datetime,actual_datetime,detention_minutes,on_time_flag,location_city,location_state
0,EVT00000001,LOAD00000001,TRIP00000001,Pickup,FAC00034,2022-01-01 18:00:00.000000,2022-01-01 20:58:55.918185,0,False,Houston,TX
1,EVT00000002,LOAD00000001,TRIP00000001,Delivery,FAC00046,2022-01-02 23:10:55.918185,2022-01-02 21:30:22.142060,230,True,Detroit,MI
2,EVT00000003,LOAD00000002,TRIP00000002,Pickup,FAC00015,2022-01-01 18:00:00.000000,2022-01-01 17:37:26.608430,62,True,Kansas City,MO

--- driver_monthly_metrics ---

C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\2727433777.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(f"SELECT * FROM {table} LIMIT 3;", conn)

,driver_id,month,trips_completed,total_miles,total_revenue,average_mpg,total_fuel_gallons,on_time_delivery_rate,average_idle_hours
0,DRV00001,2022-01-01,26,36620.0,79141.59,6.61,5574.7,0.385,8.2
1,DRV00001,2022-02-01,9,13515.0,27133.87,6.69,2095.1,0.333,6.8
2,DRV00001,2022-03-01,20,30361.0,62399.62,6.36,4792.2,0.550,7.5

--- drivers ---

C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\2727433777.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(f"SELECT * FROM {table} LIMIT 3;", conn)

,driver_id,first_name,last_name,hire_date,termination_date,license_number,license_state,date_of_birth,home_terminal,employment_status,cdl_class,years_experience
0,DRV00001,Jennifer,Hernandez,2014-10-31,None,DL673510887,WA,1973-11-07,Denver,Active,A,3.0
1,DRV00002,William,Martin,2020-10-02,None,DL128955006,GA,1976-11-03,Columbus,Active,A,20.0
2,DRV00003,Charles,Hernandez,2021-09-21,None,DL523076025,NC,1970-04-06,Salt Lake City,Active,A,19.0

--- facilities ---

C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\2727433777.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(f"SELECT * FROM {table} LIMIT 3;", conn)

,facility_id,facility_name,facility_type,city,state,latitude,longitude,dock_doors,operating_hours
0,FAC00001,Houston Distribution Center,Cross-Dock,Houston,TX,29.7604,-95.3698,125,24/7
1,FAC00002,Kansas City Hub,Cross-Dock,Kansas City,MO,39.0997,-94.5786,33,7AM-7PM
2,FAC00003,Charlotte Distribution Center,Distribution Center,Charlotte,NC,35.2271,-80.8431,138,24/7

--- fuel_purchases ---

C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\2727433777.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(f"SELECT * FROM {table} LIMIT 3;", conn)

,fuel_purchase_id,trip_id,truck_id,driver_id,purchase_date,location_city,location_state,gallons,price_per_gallon,total_cost,fuel_card_number
0,FUEL00000001,TRIP00051284,TRK00045,DRV00102,2023-10-22 05:00:00,Columbus,MN,131.6,3.399,447.31,FC567161
1,FUEL00000002,TRIP00073723,TRK00013,None,2024-08-04 08:00:00,New York,AZ,139.9,3.180,444.88,FC717910
2,FUEL00000003,TRIP00018286,TRK00024,DRV00142,2022-08-23 13:00:00,Seattle,NE,189.3,3.804,720.10,FC912816

--- loads ---

C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\2727433777.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(f"SELECT * FROM {table} LIMIT 3;", conn)

,load_id,customer_id,route_id,load_date,load_type,weight_lbs,pieces,revenue,fuel_surcharge,accessorial_charges,load_status,booking_type
0,LOAD00000001,CUST00183,RTE00019,2022-01-01,Dry Van,19178.0,13,3045.23,406.72,100.0,Completed,Spot
1,LOAD00000002,CUST00076,RTE00058,2022-01-01,Dry Van,27761.0,22,1224.48,98.61,0.0,Completed,Dedicated
2,LOAD00000003,CUST00027,RTE00048,2022-01-01,Refrigerated,35594.0,16,7171.12,792.88,0.0,Completed,Spot

--- maintenance_records ---

C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\2727433777.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(f"SELECT * FROM {table} LIMIT 3;", conn)

,maintenance_id,truck_id,maintenance_date,maintenance_type,odometer_reading,labor_hours,labor_cost,parts_cost,total_cost,facility_location,downtime_hours,service_description
0,MAINT00000001,TRK00085,2022-01-01,Inspection,400255.0,7.8,781.42,10.41,791.83,Kansas City,22.2,Emergency Inspection
1,MAINT00000002,TRK00041,2022-01-01,Tire,268041.0,0.9,80.91,3207.16,3288.07,Seattle,8.0,Scheduled Tire
2,MAINT00000003,TRK00090,2022-01-01,Preventive,698915.0,7.2,733.18,1570.57,2303.75,Miami,16.5,Routine Preventive

--- routes ---

C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\2727433777.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(f"SELECT * FROM {table} LIMIT 3;", conn)

,route_id,origin_city,origin_state,destination_city,destination_state,typical_distance_miles,base_rate_per_mile,fuel_surcharge_rate,typical_transit_days
0,RTE00001,Atlanta,GA,Chicago,IL,677.0,1.70,0.19,1
1,RTE00002,Atlanta,GA,Miami,FL,697.0,2.08,0.22,1
2,RTE00003,Chicago,IL,Los Angeles,CA,2003.0,2.55,0.29,3

--- safety_incidents ---

C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\2727433777.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(f"SELECT * FROM {table} LIMIT 3;", conn)

,incident_id,trip_id,truck_id,driver_id,incident_date,incident_type,location_city,location_state,at_fault_flag,injury_flag,vehicle_damage_cost,cargo_damage_cost,claim_amount,preventable_flag,description
0,INC00000001,TRIP00036079,TRK00006,DRV00006,2023-04-09 14:00:00,Moving Violation,Columbus,PA,True,False,12629.26,0.00,12629.26,True,Severe incident involving equipment
1,INC00000002,TRIP00032462,TRK00084,DRV00006,2023-02-19 11:00:00,Moving Violation,Columbus,NC,False,False,2700.70,14284.24,16984.94,False,Severe incident involving weather
2,INC00000003,TRIP00067583,TRK00106,DRV00119,2024-05-20 01:00:00,Customer Complaint,Seattle,OK,True,False,24302.32,0.00,24302.32,True,Minor incident involving traffic

--- trailers ---

C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\2727433777.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(f"SELECT * FROM {table} LIMIT 3;", conn)

,trailer_id,trailer_number,trailer_type,length_feet,model_year,vin,acquisition_date,status,current_location
0,TRL00001,4290,Refrigerated,53,2016,1AV889081755621178,2018-05-11,Active,Kansas City
1,TRL00002,8848,Dry Van,53,2018,1BU942062588832828,2018-11-24,Active,Kansas City
2,TRL00003,6147,Dry Van,53,2022,1AV669057807416326,2019-01-28,Active,Milwaukee

--- trips ---

C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\2727433777.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(f"SELECT * FROM {table} LIMIT 3;", conn)

,trip_id,load_id,driver_id,truck_id,trailer_id,dispatch_date,actual_distance_miles,actual_duration_hours,fuel_gallons_used,average_mpg,idle_time_hours,trip_status
0,TRIP00000001,LOAD00000001,DRV00117,TRK00035,TRL00167,2022-01-01,1314.0,26.2,183.8,7.15,3.5,Completed
1,TRIP00000002,LOAD00000002,DRV00141,TRK00108,TRL00082,2022-01-01,515.0,8.6,93.6,5.50,8.3,Completed
2,TRIP00000003,LOAD00000003,DRV00032,TRK00031,TRL00138,2022-01-01,2509.0,45.0,339.1,7.40,12.0,Completed

--- truck_utilization_metrics ---

C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\2727433777.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(f"SELECT * FROM {table} LIMIT 3;", conn)

,truck_id,month,trips_completed,total_miles,total_revenue,average_mpg,maintenance_events,maintenance_cost,downtime_hours,utilization_rate
0,TRK00001,2022-01-01,22,39269.0,84792.02,6.78,2,4380.98,63.1,0.710
1,TRK00001,2022-02-01,27,40787.0,88809.05,6.23,0,0.00,0.0,0.964
2,TRK00001,2022-03-01,34,57422.0,120453.71,6.49,0,0.00,0.0,1.097

--- trucks ---

C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\2727433777.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(f"SELECT * FROM {table} LIMIT 3;", conn)

,truck_id,unit_number,make,model_year,vin,acquisition_date,acquisition_mileage,fuel_type,tank_capacity_gallons,status,home_terminal
0,TRK00001,3463,Peterbilt,2016,1VV205190335317039,2017-04-27,18814,Diesel,200.0,Active,Omaha
1,TRK00002,6461,Kenworth,2015,1NV753749606229960,2018-10-04,26795,Diesel,150.0,Active,Seattle
2,TRK00003,2335,Peterbilt,2018,1NT803101860493229,2020-09-17,11795,Diesel,150.0,Maintenance,Atlanta

In [5]:
# Get all tables with row counts and column names
tables = pd.read_sql_query("""
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = 'public'
    ORDER BY table_name;
""", conn)

for table in tables['table_name']:
    cols = pd.read_sql_query(f"""
        SELECT column_name, data_type
        FROM information_schema.columns
        WHERE table_name = '{table}'
        ORDER BY ordinal_position;
    """, conn)
    count = pd.read_sql_query(f"SELECT COUNT(*) as rows FROM {table};", conn)
    print(f"\n--- {table} ({count['rows'][0]:,} rows) ---")
    display(cols)

--- customers (200 rows) ---

C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\1594580832.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  tables = pd.read_sql_query("""
C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\1594580832.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cols = pd.read_sql_query(f"""
C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\1594580832.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  count = pd.read_sql_query(f"SELECT COUNT(*) as rows FROM {table};", conn)

                column_name          data_type
0               customer_id  character varying
1             customer_name  character varying
2             customer_type  character varying
3         credit_terms_days            integer
4      primary_freight_type  character varying
5            account_status  character varying
6       contract_start_date               date
7  annual_revenue_potential            numeric

--- delivery_events (170,820 rows) ---

C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\1594580832.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cols = pd.read_sql_query(f"""
C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\1594580832.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  count = pd.read_sql_query(f"SELECT COUNT(*) as rows FROM {table};", conn)

           column_name                    data_type
0             event_id            character varying
1              load_id            character varying
2              trip_id            character varying
3           event_type            character varying
4          facility_id            character varying
5   scheduled_datetime  timestamp without time zone
6      actual_datetime  timestamp without time zone
7    detention_minutes                      integer
8         on_time_flag                      boolean
9        location_city            character varying
10      location_state            character varying

--- driver_monthly_metrics (4,464 rows) ---

C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\1594580832.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cols = pd.read_sql_query(f"""
C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\1594580832.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  count = pd.read_sql_query(f"SELECT COUNT(*) as rows FROM {table};", conn)

             column_name          data_type
0              driver_id  character varying
1                  month               date
2        trips_completed            integer
3            total_miles            numeric
4          total_revenue            numeric
5            average_mpg            numeric
6     total_fuel_gallons            numeric
7  on_time_delivery_rate            numeric
8     average_idle_hours            numeric

--- drivers (150 rows) ---

C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\1594580832.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cols = pd.read_sql_query(f"""
C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\1594580832.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  count = pd.read_sql_query(f"SELECT COUNT(*) as rows FROM {table};", conn)

          column_name          data_type
0           driver_id  character varying
1          first_name  character varying
2           last_name  character varying
3           hire_date               date
4    termination_date               date
5      license_number  character varying
6       license_state  character varying
7       date_of_birth               date
8       home_terminal  character varying
9   employment_status  character varying
10          cdl_class  character varying
11   years_experience            numeric

--- facilities (50 rows) ---

C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\1594580832.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cols = pd.read_sql_query(f"""
C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\1594580832.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  count = pd.read_sql_query(f"SELECT COUNT(*) as rows FROM {table};", conn)

       column_name          data_type
0      facility_id  character varying
1    facility_name  character varying
2    facility_type  character varying
3             city  character varying
4            state  character varying
5         latitude            numeric
6        longitude            numeric
7       dock_doors            integer
8  operating_hours  character varying

--- fuel_purchases (196,442 rows) ---

C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\1594580832.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cols = pd.read_sql_query(f"""
C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\1594580832.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  count = pd.read_sql_query(f"SELECT COUNT(*) as rows FROM {table};", conn)

         column_name                    data_type
0   fuel_purchase_id            character varying
1            trip_id            character varying
2           truck_id            character varying
3          driver_id            character varying
4      purchase_date  timestamp without time zone
5      location_city            character varying
6     location_state            character varying
7            gallons                      numeric
8   price_per_gallon                      numeric
9         total_cost                      numeric
10  fuel_card_number            character varying

--- loads (85,410 rows) ---

C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\1594580832.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cols = pd.read_sql_query(f"""
C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\1594580832.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  count = pd.read_sql_query(f"SELECT COUNT(*) as rows FROM {table};", conn)

            column_name          data_type
0               load_id  character varying
1           customer_id  character varying
2              route_id  character varying
3             load_date               date
4             load_type  character varying
5            weight_lbs            numeric
6                pieces            integer
7               revenue            numeric
8        fuel_surcharge            numeric
9   accessorial_charges            numeric
10          load_status  character varying
11         booking_type  character varying

--- maintenance_records (2,920 rows) ---

C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\1594580832.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cols = pd.read_sql_query(f"""
C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\1594580832.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  count = pd.read_sql_query(f"SELECT COUNT(*) as rows FROM {table};", conn)

            column_name          data_type
0        maintenance_id  character varying
1              truck_id  character varying
2      maintenance_date               date
3      maintenance_type  character varying
4      odometer_reading            numeric
5           labor_hours            numeric
6            labor_cost            numeric
7            parts_cost            numeric
8            total_cost            numeric
9     facility_location  character varying
10       downtime_hours            numeric
11  service_description               text

--- routes (58 rows) ---

C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\1594580832.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cols = pd.read_sql_query(f"""
C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\1594580832.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  count = pd.read_sql_query(f"SELECT COUNT(*) as rows FROM {table};", conn)

              column_name          data_type
0                route_id  character varying
1             origin_city  character varying
2            origin_state  character varying
3        destination_city  character varying
4       destination_state  character varying
5  typical_distance_miles            numeric
6      base_rate_per_mile            numeric
7     fuel_surcharge_rate            numeric
8    typical_transit_days            integer

--- safety_incidents (170 rows) ---

C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\1594580832.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cols = pd.read_sql_query(f"""
C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\1594580832.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  count = pd.read_sql_query(f"SELECT COUNT(*) as rows FROM {table};", conn)

            column_name                    data_type
0           incident_id            character varying
1               trip_id            character varying
2              truck_id            character varying
3             driver_id            character varying
4         incident_date  timestamp without time zone
5         incident_type            character varying
6         location_city            character varying
7        location_state            character varying
8         at_fault_flag                      boolean
9           injury_flag                      boolean
10  vehicle_damage_cost                      numeric
11    cargo_damage_cost                      numeric
12         claim_amount                      numeric
13     preventable_flag                      boolean
14          description                         text

--- trailers (180 rows) ---

C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\1594580832.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cols = pd.read_sql_query(f"""
C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\1594580832.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  count = pd.read_sql_query(f"SELECT COUNT(*) as rows FROM {table};", conn)

        column_name          data_type
0        trailer_id  character varying
1    trailer_number  character varying
2      trailer_type  character varying
3       length_feet            integer
4        model_year            integer
5               vin  character varying
6  acquisition_date               date
7            status  character varying
8  current_location  character varying

C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\1594580832.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cols = pd.read_sql_query(f"""
C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\1594580832.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  count = pd.read_sql_query(f"SELECT COUNT(*) as rows FROM {table};", conn)

--- trips (85,410 rows) ---

              column_name          data_type
0                 trip_id  character varying
1                 load_id  character varying
2               driver_id  character varying
3                truck_id  character varying
4              trailer_id  character varying
5           dispatch_date               date
6   actual_distance_miles            numeric
7   actual_duration_hours            numeric
8       fuel_gallons_used            numeric
9             average_mpg            numeric
10        idle_time_hours            numeric
11            trip_status  character varying

--- truck_utilization_metrics (3,312 rows) ---

C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\1594580832.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cols = pd.read_sql_query(f"""
C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\1594580832.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  count = pd.read_sql_query(f"SELECT COUNT(*) as rows FROM {table};", conn)

          column_name          data_type
0            truck_id  character varying
1               month               date
2     trips_completed            integer
3         total_miles            numeric
4       total_revenue            numeric
5         average_mpg            numeric
6  maintenance_events            integer
7    maintenance_cost            numeric
8      downtime_hours            numeric
9    utilization_rate            numeric

--- trucks (120 rows) ---

C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\1594580832.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cols = pd.read_sql_query(f"""
C:\Users\gianc\AppData\Local\Temp\ipykernel_19616\1594580832.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  count = pd.read_sql_query(f"SELECT COUNT(*) as rows FROM {table};", conn)

              column_name          data_type
0                truck_id  character varying
1             unit_number  character varying
2                    make  character varying
3              model_year            integer
4                     vin  character varying
5        acquisition_date               date
6     acquisition_mileage            integer
7               fuel_type  character varying
8   tank_capacity_gallons            numeric
9                  status  character varying
10          home_terminal  character varying